engines:
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
      global-require:
        enabled: false
    exclude_fingerprints:
    - 8fd38171704aced90dbaa8439100b67b # Silence linter about process.exit
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - app/**/*.{scss,sass,css,js,html}
  - src/**/*.js
  - test/**/*.js
exclude_paths:
  - Gruntfile.js
  - test/karma.conf.js
